FWVERSION = "fwversion"
HUB_NAME = "hubName"
CONFIG = "config"

FIRMWARE = "firmware"
FIRMWARE_MAINPROCESSOR = "mainProcessor"
FIRMWARE_NAME = "name"
FIRMWARE_REVISION = "revision"
FIRMWARE_SUB_REVISION = "subRevision"
FIRMWARE_BUILD = "build"

NETWORK_STATUS = "networkStatus"
MAC_ADDRESS_IN_USERDATA = "macAddress"
SERIAL_NUMBER_IN_USERDATA = "serialNumber"
HUB_NAME = "hubName"

LEGACY_DEVICE_SUB_REVISION = 1
LEGACY_DEVICE_REVISION = 0
LEGACY_DEVICE_BUILD = 0
LEGACY_DEVICE_MODEL = "PowerView Hub"

DEFAULT_LEGACY_MAINPROCESSOR = {
    FIRMWARE_REVISION: LEGACY_DEVICE_REVISION,
    FIRMWARE_SUB_REVISION: LEGACY_DEVICE_SUB_REVISION,
    FIRMWARE_BUILD: LEGACY_DEVICE_BUILD,
    FIRMWARE_NAME: LEGACY_DEVICE_MODEL,
}

API_PATH_FWVERSION = "api/fwversion"

USER_DATA = "userData"

ATTR_ICON_ID = "iconId"
ATTR_COLOR_ID = "colorId"
ATTR_SCENE_ID = "sceneId"
ATTR_SHADE_ID = "shadeId"
ATTR_ROOM_ID = "roomId"

ATTR_NAME = "name"
ATTR_NAME_UNICODE = "name_unicode"

ATTR_POSKIND1 = "posKind1"
ATTR_POSKIND2 = "posKind2"
ATTR_POSITION1 = "position1"
ATTR_POSITION2 = "position2"
ATTR_POSITION = "position"
ATTR_COMMAND = "command"
ATTR_MOVE = "move"
ATTR_PRIMARY = "primary"
ATTR_SECONDARY = "secondary"
ATTR_TILT = "tilt"
ATTR_VELOCITY = "velocity"

ATTR_OPEN_POSITION = "open_position"
ATTR_CLOSE_POSITION = "close_position"
ATTR_ALLOWED_POSITIONS = "allowed_positions"

ATTR_CAPABILITIES = "capabilities"
ATTR_POSITION_DATA = "positions"
ATTR_SCENE = "scene"
ATTR_SHADE = "shade"
ATTR_ROOM = "room"
ATTR_SCENE_MEMBER = "sceneMember"
ATTR_USER_DATA = "user"
ATTR_TYPE = "type"
ATTR_TYPES = "types"
ATTR_ID = "id"
ATTR_BATTERY_KIND = "batteryKind"
ATTR_POWER_TYPE = "powerType"

MIN_POSITION = 0
MID_POSITION = 0.5
MAX_POSITION = 1
MID_POSITION_V2 = 32767
MAX_POSITION_V2 = 65535


POSKIND_NONE = 0
POSKIND_PRIMARY = 1
POSKIND_SECONDARY = 2
POSKIND_VANE = 3
POSKIND_ERROR = 4
